### ISSUE TITLE
Building 'outside' of source directory fails.

### ISSUE THREAD

**Issue by MichaelTiernan** [envmodules/modules#558]
While this is a bug, it is not a brick wall preventing building due to the obvious workaround of multiple copies of the source tree.

### Describe the bug
Traditionally (and by design) *usually* building outside of the source tree is permitted and enabled.

As an example....
~~~
Buildspace/+
           +--> Envmodules            (Source)
           +--> Target_1              (CentOS)
           +--> Target_2              (Ubuntu)
~~~

An example workflow might look like this: (On a `CentOS` system with `Envmodules` repo remote mounted.)
~~~console
$ cd Buildspace
$ cd Target_1
$ ../Envmodules/configure {plus flags needed}

... build specific to CentOS proceeds ...
~~~

Then on my Ubuntu system: (On a `Ubuntu 22.x` system with `Envmodules` repo remote mounted.)
~~~console
$ cd Buildspace
$ cd Target_2
$ ../Envmodules/configure {plus flags needed}

... build specific to Ubuntu proceeds ...
~~~

And yes, this is a normal use/behavior of the GNU Autoconf tool.

### To Reproduce  

Example run:
~~~console
$ cd Buildspace
$ cd Target
$ ../Envmodules/configure
checking for uname... /usr/bin/uname
checking for make... /usr/bin/make
checking for sed... /usr/bin/sed
checking for runtest... not found
WARNING: Install `dejagnu' if you want to run the testsuite
checking for manpath... /usr/bin/manpath
checking for sphinx-build... not found
checking for sphinx-1.0-build... not found
WARNING: Install `sphinx-build' if you want to build the documentation
checking for tclsh... /usr/bin/tclsh
checking for python... /usr/bin/python
checking for ps... /usr/bin/ps
checking for basename... /usr/bin/basename
checking for logger... /usr/bin/logger
checking for less... /usr/bin/less
checking for nagelfar.tcl... not found
WARNING: nagelfar.tcl could not be found
checking for autoreconf... /usr/bin/autoreconf
--- preparing extension library sources ----------
../Envmodules/configure: line 1170: pushd: lib: No such file or directory
~~~

### Expected behavior
I expected the configure and build to proceed functionally the same as if done in the source dir (in this example `Envmodules`)
However, the build would not introduce any "non source" files specific to a platform into the source tree.

**Comment by xdelaruelle** [comment]
Many thanks @MichaelTiernan for your report.

Until now, it was required to run the `configure` script from the directory where this file was stored.

But no problem to improve that and make this script able to be run from a different current working directory.
